# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "TestTask"
client_id = "1debe625307fd191f79cf194cd50fedc"
application_url = "https://conventional-composition-ears-measure.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_script_tags,write_script_tags,read_themes,write_themes,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://conventional-composition-ears-measure.trycloudflare.com/auth/callback",
  "https://conventional-composition-ears-measure.trycloudflare.com/auth/shopify/callback",
  "https://conventional-composition-ears-measure.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testtask-regional-capital-app.myshopify.com"
